name: ML Training Pipeline

on:
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

        
      - name: Install and Run Linter
        run: |
          pip install flake8
          # E9 (Syntax Errors), F63 (Logic/Comparison Errors), F7 (Structural Syntax Errors), F82 (Undefined Variables)
          flake8 train.py --select=E9,F63,F7,F82

  train:
    needs: linter
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[run-train]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Training Script
        run: python train.py 2> error_logs.txt

      - name: Upload Error Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: error_logs.txt

      - name: Cleanup Volumes
        if: always()
        run: echo "Cleaning up temporary cloud volumes..."